name: Deploy to Zomro

on:
  push:
    branches:
      - main
      - "основной"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get files from GitHub
        uses: actions/checkout@v4

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ZOMRO_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -p ${{ secrets.ZOMRO_PORT }} ${{ secrets.ZOMRO_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy files to Zomro
        run: |
          rsync -avz --delete \
            --exclude ".git" \
            --exclude ".github" \
            -e "ssh -i ~/.ssh/deploy_key -p ${{ secrets.ZOMRO_PORT }}" \
            ./ ${{ secrets.ZOMRO_USER }}@${{ secrets.ZOMRO_HOST }}:${{ secrets.ZOMRO_PATH }}
